In [1]:
import numpy as np

In [2]:
# Create two basic arrays
n1 = np.array([1, 2, 3])
n2 = np.array([4, 5, 6])

print(n1)
print(n2)

[1 2 3]
[4 5 6]


In [3]:
# Define array and set its shape to 1x3
n1 = np.array([[22, 33, 44]])

print(n1)
print(n2)

[[22 33 44]]
[4 5 6]


In [4]:
# Add [2, 2, 2] to n1
result = n1 + np.array([2, 2, 2])
print(result)

[[24 35 46]]


In [5]:
# Subtract [2, 3, 4] from n1
result = n1 - np.array([2, 3, 4])
print(result)

[[20 30 40]]


In [6]:
# Multiply n1 by 25
result = n1 * 25
print(result)

[[ 550  825 1100]]


In [7]:
# Perform element-wise multiplication
result = np.multiply(n1, [11, 12, 13])
print(result)

[[242 396 572]]


In [8]:
# Reshape n1 to (3, 1)
# Create a 1x4 matrix filled with 3s
# Perform matrix multiplication using dot product
n1_reshaped = n1.reshape(3, 1)
threes = np.full((1, 4), 3)
result = np.dot(n1_reshaped, threes)
print(result)

[[ 66  66  66  66]
 [ 99  99  99  99]
 [132 132 132 132]]


In [9]:
# Convert n1 to a 1D vector or handle transpose product
# Since n1 has shape (1, 3), np.dot(n1, n1.T) calculates the dot product
result = np.dot(n1, n1.T)
print(result)

[[3509]]


In [10]:
# Prime numbers between 1 and 23: [2, 3, 5, 7, 11, 13, 17, 19, 23]
# Compute inverse matrix
# Multiply v1 and v2, then round to handle floating-point precision
v1 = np.array([
    [2, 3, 5],
    [7, 11, 13],
    [17, 19, 23]
])
v2 = np.linalg.inv(v1)
identity = np.round(np.dot(v1, v2))
print(identity)

[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [11]:
# 1. Square root of all elements
print("Square Root:")
print(np.sqrt(v1))

# 2. Exponential (e^x) of all elements
print("\nExponential:")
print(np.exp(v1))

# 3. Sum of all elements
print("\nSum of elements:")
print(np.sum(v1))

Square Root:
[[1.41421356 1.73205081 2.23606798]
 [2.64575131 3.31662479 3.60555128]
 [4.12310563 4.35889894 4.79583152]]

Exponential:
[[7.38905610e+00 2.00855369e+01 1.48413159e+02]
 [1.09663316e+03 5.98741417e+04 4.42413392e+05]
 [2.41549528e+07 1.78482301e+08 9.74480345e+09]]

Sum of elements:
100
